# -*- coding: utf-8 -*-
"""2020-05-22.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/169wHb84i5-P9ubm2gvd0M2-XktmWxYxT
"""

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"]
for i, val in enumerate(avengers):
    print("{}: {}".format(i, val))

avengers = ["The Avengers", "Avengers: Age of Ultron", "Avengers: Infinity War", "Avengers: Endgame"] #隨堂練習
for i, val in enumerate(avengers):
    print("第 {} 部上映的復仇者聯盟是：{}".format(i+1, val))