# -*- coding: utf-8 -*-
"""2020-03-27.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10mrWi-hcPg_D8JIJ8CTCIwqtgudYhzJ0
"""

tempc = input("請輸入現在的攝氏氣溫：") #1
tempc = int(tempc)
tempf = tempc*9/5 + 32
print("攝氏{}度，華氏{}度".format (tempc, tempf))

shaq_height = 216 #2
shaq_weight = 147
shaq_bmi = shaq_weight/(shaq_height/100)**2 # 將身高轉換為以公尺為單位

print(shaq_bmi)

ross_said = "Let's put aside the fact that you \"accidentally\" pick up my grandmother's ring." #3
print(ross_said)

city = input("請輸入您所在的城市：") #4
weather = input("請輸入現在的天氣：")
print("我在{}，天氣{}".format(city, weather))

player_height = float(input("請輸入球員身高(公尺):"))
player_weight = float(input("請輸入球員體重(公斤):"))
player_bmi = player_weight / player_height**2
bmi_label = None
if player_bmi > 30:
    bmi_label = 'Obese'
elif player_bmi > 25:
    bmi_label = 'Overweight'
elif player_bmi > 18.5:
    bmi_label = 'Normal weight'
else:
    bmi_label = 'Underweight'
print(player_bmi)
print(bmi_label)