# -*- coding: utf-8 -*-
"""2020-03-20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VDm_plP38rXS5lqd9mtZTkSDip5erkm3
"""

movie_title = "Avengers: Endgame" #隨堂練習
movie_length = 181
movie_rating = 8.4
print(movie_title)
print(movie_length)
print(movie_rating)
print(type(movie_title))
print(type(movie_length))
print(type(movie_rating))

